# Port of home-manager-modules/niri/config.kdl.nix to OmniWM (macOS).
# Mod = Command, matching the aerospace binds this replaces.
#
# Niri concepts that have no OmniWM equivalent, and are therefore dropped:
#   blur/noise/opacity window rules, shaders, tab-indicator + insert-hint styling,
#   xkb layout/repeat (macOS system prefs), spawn-at-startup, close-window,
#   move-workspace-up/down (reordering workspaces), keyboard-shortcuts-inhibit.
# Launcher-ish binds (Mod+T, Mod+R/B/D/Q/U/S menus, screenshots) live in skhd.nix —
# OmniWM hotkeys can only run window-manager commands, never external processes.
{outputs, ...}: let
  p = outputs.palette;

  hexDigits = {
    "0" = 0;
    "1" = 1;
    "2" = 2;
    "3" = 3;
    "4" = 4;
    "5" = 5;
    "6" = 6;
    "7" = 7;
    "8" = 8;
    "9" = 9;
    "a" = 10;
    "b" = 11;
    "c" = 12;
    "d" = 13;
    "e" = 14;
    "f" = 15;
    "A" = 10;
    "B" = 11;
    "C" = 12;
    "D" = 13;
    "E" = 14;
    "F" = 15;
  };
  hexByte = s: 16 * hexDigits.${builtins.substring 0 1 s} + hexDigits.${builtins.substring 1 1 s};

  # Whole numbers must still serialize as TOML floats — the decoder wants Double.
  float = v: let
    s = toString v;
  in
    if builtins.match ".*\\..*" s == null
    then "${s}.0"
    else s;
  channel = hex: offset: float ((hexByte (builtins.substring offset 2 (builtins.substring 1 6 hex))) / 255.0);

  # OmniWM stores colors as float RGBA components, one key per channel.
  color = table: hex: alpha: ''
    [${table}]
    red = ${channel hex 0}
    green = ${channel hex 2}
    blue = ${channel hex 4}
    alpha = ${float alpha}
  '';

  bind = id: keys: ''  { id = "${id}", binding = "${keys}" },'';
  binds = keys: builtins.concatStringsSep "\n" (builtins.attrValues (builtins.mapAttrs bind keys));
in ''
  # Generated by nix — edits here are overwritten on the next home-manager switch.

  hotkeys = [
  ${binds {
    # Focus (niri Mod+H/J/K/L). One trigger per action, so the niri arrow-key
    # duplicates of every hjkl bind are gone.
    "focus.left" = "Command+H";
    "focus.down" = "Command+J";
    "focus.up" = "Command+K";
    "focus.right" = "Command+L";
    "focusColumnFirst" = "Command+Home";
    "focusColumnLast" = "Command+End";

    # Workspaces. Only 1-4 get focus binds, like niri.
    "switchWorkspace.0" = "Command+1";
    "switchWorkspace.1" = "Command+2";
    "switchWorkspace.2" = "Command+3";
    "switchWorkspace.3" = "Command+4";
    "moveToWorkspace.0" = "Command+Shift+1";
    "moveToWorkspace.1" = "Command+Shift+2";
    "moveToWorkspace.2" = "Command+Shift+3";
    "moveToWorkspace.3" = "Command+Shift+4";
    "moveToWorkspace.4" = "Command+Shift+5";
    "moveToWorkspace.5" = "Command+Shift+6";
    # niri Mod+I / Mod+Page_Down. Page Up would be dead weight on the laptop.
    "switchWorkspace.previous" = "Command+I";
    "switchWorkspace.next" = "Command+Page Down";
    "moveColumnToWorkspaceUp" = "Command+Control+I";
    "moveColumnToWorkspaceDown" = "Command+Control+Page Down";

    # Monitors. OmniWM only walks the monitor list, so niri's Mod+Alt+J/K
    # (focus-monitor-down/up) have nowhere to go.
    "focusMonitorPrevious" = "Command+Option+H";
    "focusMonitorNext" = "Command+Option+L";
    "focusMonitorLast" = "Command+Option+Grave";
    # niri moves the column; OmniWM moves the whole workspace.
    "moveWorkspaceToMonitor.left" = "Command+Option+Shift+H";
    "moveWorkspaceToMonitor.down" = "Command+Option+Shift+J";
    "moveWorkspaceToMonitor.up" = "Command+Option+Shift+K";
    "moveWorkspaceToMonitor.right" = "Command+Option+Shift+L";

    # Move. moveColumn = niri move-column-left/right, move = within the column.
    "moveColumn.left" = "Command+Shift+H";
    "moveColumn.right" = "Command+Shift+L";
    "move.down" = "Command+Shift+J";
    "move.up" = "Command+Shift+K";
    "move.left" = "Command+Left Bracket";
    "move.right" = "Command+Right Bracket";
    "consumeWindowIntoColumn" = "Command+Comma";
    "expelWindowFromColumn" = "Command+Period";
    "moveColumnToFirst" = "Command+Control+Home";
    "moveColumnToLast" = "Command+Control+End";

    # Sizing. Primary span = column width, secondary span = window height.
    # niri's ±30px binds become ±10% — OmniWM has no pixel-step action.
    "setContainerPrimarySpan.decrease10Percent" = "Command+Minus";
    "setContainerPrimarySpan.increase10Percent" = "Command+Equal";
    "setWindowSecondarySpan.decrease10Percent" = "Command+Shift+Minus";
    "setWindowSecondarySpan.increase10Percent" = "Command+Shift+Equal";
    "setWindowPrimarySpan.decrease10Percent" = "Command+Control+H";
    "setWindowPrimarySpan.increase10Percent" = "Command+Control+L";
    "cycleSizeForward" = "Command+Control+W";
    "cycleSizeBackward" = "Command+Control+Shift+W";
    "cycleWindowSecondarySpanForward" = "Command+Control+Shift+R";
    "resetWindowSecondarySpan" = "Command+Control+R";
    "toggleContainerFullPrimarySpan" = "Command+F";
    "expandContainerToAvailablePrimarySpan" = "Command+Control+F";
    # niri Mod+C, moved off Command+C so copy keeps working.
    "centerColumn" = "Command+Control+C";
    "centerVisibleColumns" = "Command+Control+Shift+C";

    # Layout and windows.
    "toggleFullscreen" = "Command+M";
    "toggleNativeFullscreen" = "Command+Shift+M";
    "toggleColumnTabbed" = "Command+Shift+W";
    "toggleFocusedWindowFloating" = "Command+Shift+F";
    "raiseAllFloatingWindows" = "Command+Control+Shift+F";
    "toggleOverview" = "Command+O";
    "toggleWorkspaceLayout" = "Command+Control+Shift+L";

    # OmniWM extras with no niri counterpart.
    "toggleQuakeTerminal" = "Command+Grave";
    "openCommandPalette" = "Command+Shift+Space";
    "openMenuAnywhere" = "Command+Control+M";
    "toggleWorkspaceBarVisibility" = "Command+Control+B";
    "toggleScratchpadWindow" = "Command+Control+S";
    "assignFocusedWindowToScratchpad" = "Command+Control+Shift+S";
  }}
  ]

  # Per-monitor overrides are set up interactively (Settings > Monitors), which
  # needs display UUIDs. Declared empty so the strict decode path succeeds.
  monitorBarOverrides = []
  monitorOrientationOverrides = []
  monitorNiriOverrides = []
  monitorDwindleOverrides = []
  monitorGapOverrides = []
  monitorRoutingOverrides = []

  [general]
  hotkeysEnabled = true
  systemHyperTrigger = "None"
  defaultLayoutType = "niri"
  preventSleepEnabled = false
  updateChecksEnabled = false
  ipcEnabled = true
  animationsEnabled = true

  [focus]
  # focus-follows-mouse + warp-mouse-to-focus mode="center-xy"
  followsMouse = true
  lockModifier = "off"
  moveMouseToFocusedWindow = true
  followsWindowToMonitor = true
  # niri focus-column-or-monitor-left / move-column-left-or-to-monitor-left
  crossesMonitorAtEdge = true
  moveCrossesMonitorAtEdge = true

  [mouseWarp]
  enabled = true
  margin = 1
  constrainToArrangement = false

  [routing]
  mode = "macOS"

  [gaps]
  size = 16.0

  [gaps.outer]
  left = 16.0
  right = 16.0
  top = 16.0
  bottom = 16.0

  [niri]
  visibleContainerCount = 2
  infiniteLoop = false
  centerFocusedColumn = "onOverflow"
  alwaysCenterSingleColumn = true
  # Lone window keeps its column width instead of filling the screen, so
  # always-center-single-column is actually visible.
  singleWindowFit = "container_primary_span"
  containerPrimarySpanPresets = [0.33333, 0.5, 0.66667]
  defaultContainerPrimarySpan = 0.5

  [dwindle]
  smartSplit = false
  defaultSplitRatio = 1.0
  splitWidthMultiplier = 1.0
  singleWindowFit = "fill"
  useGlobalGaps = true
  moveToRootStable = true

  [borders]
  # services.jankyborders (darwin/configuration.nix) already draws these.
  enabled = false
  width = 1.0

  ${color "borders.color" p.base04 1.0}
  [overview]
  zoom = 1.0

  ${color "overview.backdrop" p.base00 1.0}
  ${color "overview.windowBorders.normal" p.base03 1.0}
  ${color "overview.windowBorders.hovered" p.base0D 1.0}
  ${color "overview.windowBorders.selected" p.base04 1.0}
  [workspaceBar]
  enabled = true
  showLabels = true
  showFloatingWindows = false
  windowLevel = "popup"
  position = "overlappingMenuBar"
  notchMode = "moveBelowMenuBar"
  notchActiveZoneWidth = 180.0
  systemStatsButton = false
  deduplicateAppIcons = true
  hideEmptyWorkspaces = false
  excludedBundleIDs = []
  reserveLayoutSpace = false
  revealModifier = "off"
  revealHoldMilliseconds = 200.0
  height = 24.0
  backgroundOpacity = 0.1
  xOffset = 0.0
  yOffset = 0.0

  [workspaceBar.iconOverrides]

  ${color "workspaceBar.accentColor" p.base0D 1.0}
  ${color "workspaceBar.textColor" p.base05 1.0}
  [gestures]
  scrollEnabled = true
  scrollSensitivity = 5.0
  # Mod+WheelScroll column navigation, closest available modifier.
  scrollModifierKey = "optionShift"
  mouseResizeModifierKey = "option"
  fingerCount = 3
  # niri touchpad { natural-scroll }
  invertDirection = true
  trackpadScrollStyle = "snap"
  workspaceSwipeEnabled = false
  workspaceSwipeFingerCount = 3
  workspaceSwipeAxis = "vertical"

  [statusBar]
  showWorkspaceName = true
  showAppNames = false
  useWorkspaceId = false

  [hiddenBar]
  enabled = false
  hiddenBundleIDs = []
  rehideIntervalSeconds = 5.0

  [clipboard]
  historyEnabled = false
  maxItems = 200
  maxItemBytes = 8388608
  maxTotalBytes = 67108864

  [quakeTerminal]
  # Not a niri feature; kitty via skhd (Command+T) is still the real terminal.
  enabled = true
  position = "top"
  widthPercent = 100.0
  heightPercent = 40.0
  animationDuration = 0.2
  autoHide = false
  opacity = 0.95
  backgroundEffect = "standardBlur"
  backgroundBlurRadius = 30
  monitorMode = "focusedWindow"

  [appearance]
  # stylix polarity = "light"
  mode = "light"

  # Workspaces need stable UUIDs, otherwise every switch reshuffles them.
  [[workspaces]]
  id = "9E1B4C10-0001-4A00-9C00-000000000001"
  name = "1"
  layoutType = "niri"
  monitorAssignment = { type = "main" }

  [[workspaces]]
  id = "9E1B4C10-0001-4A00-9C00-000000000002"
  name = "2"
  layoutType = "niri"
  monitorAssignment = { type = "main" }

  [[workspaces]]
  id = "9E1B4C10-0001-4A00-9C00-000000000003"
  name = "3"
  layoutType = "niri"
  monitorAssignment = { type = "main" }

  [[workspaces]]
  id = "9E1B4C10-0001-4A00-9C00-000000000004"
  name = "4"
  layoutType = "niri"
  monitorAssignment = { type = "main" }

  [[workspaces]]
  id = "9E1B4C10-0001-4A00-9C00-000000000005"
  name = "5"
  layoutType = "niri"
  monitorAssignment = { type = "secondary" }

  [[workspaces]]
  id = "9E1B4C10-0001-4A00-9C00-000000000006"
  name = "6"
  layoutType = "niri"
  monitorAssignment = { type = "secondary" }

  # niri window-rule match app-id="popup" → open-floating
  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000001"
  bundleId = ""
  axSubrole = "AXDialog"
  layout = "float"

  # niri window-rule match title="^Picture-in-Picture$" → open-floating
  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000002"
  bundleId = ""
  titleRegex = "^Picture-in-Picture$"
  layout = "float"

  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000003"
  bundleId = "com.apple.systempreferences"
  layout = "float"

  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000004"
  bundleId = "com.apple.calculator"
  layout = "float"

  # niri default-column-width { proportion 0.5; }
  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000005"
  bundleId = "net.kovidgoyal.kitty"
  initialContainerPrimarySpan = 0.5
  minWidth = 90.0
  minHeight = 48.0

  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000006"
  bundleId = "app.zen-browser.zen"
  minWidth = 500.0
  minHeight = 495.0

  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000007"
  bundleId = "com.google.Chrome"
  minWidth = 500.0
  minHeight = 375.0

  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000008"
  bundleId = "com.spotify.client"
  minWidth = 800.0
  minHeight = 600.0

  [[appRules]]
  id = "9E1B4C10-0002-4A00-9C00-000000000009"
  bundleId = "com.tinyspeck.slackmacgap"
  minWidth = 800.0
  minHeight = 500.0
''
