[buildPlans.IosevkaTerm]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaTerm.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaTerm.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaTerm.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTerm.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaTerm.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaTerm.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaTerm.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaTerm.weights.Heavy]
shape = 900
menu = 900
css = 900