[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = false
datetime_format = "%a %b %e %T %Y"
username_shown = true
palette = "vibrant"
title_shown = true
margin = 0
badges = true
theme = "light"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = true
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = true
betterttv_emotes = true
seventv_emotes = true
frankerfacez_emotes = true
favorite_channels = ["M0xyy"]
recent_channel_count = 5
border_type = "plain"
hide_chat_border = false
right_align_usernames = false
show_unsupported_screen_size = true
