{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  ...
}: let
  brightness = 0;
  contrast = 0;
  fillColor = outputs.palette.base00;
  saturation = 100;
in {
  imports = with inputs; [
    home-manager.nixosModules.home-manager
    stylix.nixosModules.stylix

    xremap-flake.nixosModules.default

    (import ../nix-modules/nix.nix {inherit inputs lib config;})
    (import ../nix-modules/nixpkgs.nix {inherit inputs outputs;})
    ../nix-modules/samba.nix
    ../nix-modules/xremap.nix
    ./maintenance.nix
  ];

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = {inherit inputs outputs;};
    users.hedonicadapter = import ./home.nix;
    backupFileExtension = "backup";
  };

  environment.pathsToLink = ["/share/zsh"];
  environment.systemPackages = with pkgs; [
    # inputs.neovim-flake.packages.${system}.nvim
    onlyoffice-desktopeditors
    wine
    winetricks
    gcc
    python311Packages.cmake
    nodejs_22
    xorg.xmodmap
    git
    nix-output-monitor
    kicad
    openscad

    bluetuith
    fastfetch
    polkit_gnome
    lm_sensors
    atac
    zoxide
    ripgrep
    fd
    swappy
    easyeffects
    pulseaudio
    playerctl

    bc
    wl-clipboard
    cliphist
    wl-clip-persist
    vscode
    obsidian
    font-manager
    fsearch

    libvpx
    dav1d
    ffmpeg-full
    libva-utils
    vdpauinfo

    mangohud
    goverlay
  ];

  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
    # Defaults: package = pkgs.hyprland, portalPackage = pkgs.xdg-desktop-portal-hyprland.
  };

  programs.niri = {
    enable = true;
  };

  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true;
    dedicatedServer.openFirewall = true;
    gamescopeSession.enable = true;
  };
  programs.gamemode.enable = true;
  programs.gamemode.enableRenice = true;

  environment.sessionVariables = {
    NIXOS_OZONE_WL = "1";
    TERM = "kitty";
    MOZ_ENABLE_WAYLAND = "1";
    # LIBVA_DRIVER_NAME = "i915"; # INFO: Use "i915" for older Intel or "radeonsi" for AMD
    # MOZ_DISABLE_RDD_SANDBOX = "1";
    # Only set these if Hyprland continues to freeze
    # GBM_BACKEND = "nvidia-drm";
    # __GLX_VENDOR_LIBRARY_NAME = "nvidia";
  };

  stylix = {
    enable = true;
    image = ../wallpapers/Frame21.png;
    # pkgs.runCommand "dimmed-background.png" {} ''
    #   ${pkgs.imagemagick}/bin/magick "${inputImage}" -brightness-contrast ${
    #     toString brightness
    #   },${toString contrast} -modulate 100,${
    #     toString saturation
    #   } -fill "${fillColor}" $out
    # '';
    polarity = "dark";
    base16Scheme = outputs.palette;
    targets = {
      gnome.enable = true;
      gtk.enable = true;
    };

    fonts = {
      serif = {
        package = pkgs.merriweather;
        name = "Merriweather";
      };

      sansSerif = {
        package = pkgs.ultimate-oldschool-pc-font-pack;
        name = "Mx437 DOS/V re. JPN30";
      };

      monospace = {
        package = pkgs.ultimate-oldschool-pc-font-pack;
        name = "Mx437 DOS/V re. JPN30";
      };

      emoji = {
        package = pkgs.noto-fonts-color-emoji;
        name = "Noto Color Emoji";
      };

      sizes.applications = 14;
      sizes.desktop = 14;
      sizes.popups = 14;
      sizes.terminal = 14;
    };

    # cursor = {
    # package = pkgs.callPackage ../home-manager/oxygen-neon-cursors.nix {};
    #   name = "rah";
    #   size = 200;
    # };
  };

  security.polkit.enable = true;

  # formerly hardware.opengl
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;
  # environment.sessionVariables = {LIBVA_DRIVER_NAME = "iHD";}; # Force intel-media-driver
  # environment.sessionVariables = {
  #   LIBVA_DRIVER_NAME = "nvidia";
  #   GBM_BACKEND = "nvidia-drm";
  #   __GLX_VENDOR_LIBRARY_NAME = "nvidia";
  # }; # Force nvidia driver

  hardware.logitech.wireless.enable = true;
  hardware.logitech.wireless.enableGraphical = true;

  boot = {
    kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-latest;
    tmp.cleanOnBoot = true;
    loader.grub.timeoutStyle = false;
    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot = {
        enable = true;
        editor = true;
        configurationLimit = 100;
      };
    };

    kernel.sysctl."vm.max_map_count" = 1048576;
  };

  # hardware.fancontrol = {
  #   enable = true;
  #   config = ''
  #     # Configuration file generated by pwmconfig
  #     INTERVAL=10
  #     DEVPATH=hwmon3=devices/virtual/thermal/thermal_zone2 hwmon4=devices/platform/f71882fg.656
  #     DEVNAME=hwmon3=soc_dts1 hwmon4=f71869a
  #     FCTEMPS=hwmon4/device/pwm1=hwmon3/temp1_input
  #     FCFANS=hwmon4/device/pwm1=hwmon4/device/fan1_input
  #     MINTEMP=hwmon4/device/pwm1=35
  #     MAXTEMP=hwmon4/device/pwm1=65
  #     MINSTART=hwmon4/device/pwm1=150
  #     MINSTOP=hwmon4/device/pwm1=0
  #   '';
  # };

  powerManagement.cpuFreqGovernor = "performance";
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Stockholm";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.inputMethod = {
    type = "ibus";
    enable = true;
  };
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "sv_SE.UTF-8";
    LC_IDENTIFICATION = "sv_SE.UTF-8";
    LC_MEASUREMENT = "sv_SE.UTF-8";
    LC_MONETARY = "sv_SE.UTF-8";
    LC_NAME = "sv_SE.UTF-8";
    LC_NUMERIC = "sv_SE.UTF-8";
    LC_PAPER = "sv_SE.UTF-8";
    LC_TELEPHONE = "sv_SE.UTF-8";
    LC_TIME = "sv_SE.UTF-8";
  };
  console.keyMap = "sv-latin1";

  security.rtkit.enable = true;

  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
  services.gvfs.enable = true; # AGS docs: "In order for network cover art urls to be cached (spotify for example) make sure gvfs is enabled."

  virtualisation.docker.enable = true;
  virtualisation.docker.rootless = {
    enable = true;
    setSocketVariable = true;
  };
  virtualisation.docker.daemon.settings = {
    data-root = "~/Documents/coding/docker";
  };

  networking.extraHosts = ''
    127.0.0.1 localhost
    ::1 localhost
    127.0.0.2 ${config.networking.hostName}
  '';
  networking.nameservers = ["8.8.8.8" "8.8.4.4"];

  users.users = {
    hedonicadapter = {
      isNormalUser = true;
      openssh.authorizedKeys.keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ3K6FA+Gy2wNolnPVeM7sNoy/Q9wj4mn3STOsF4ySOT sam.herman@xenit.se"];
      extraGroups = ["networkmanager" "wheel" "docker" "dialout" "input" "gamemode" "ydotool"];
    };
  };

  systemd.sleep.settings.Sleep = {
    AllowSuspend = "no";
    AllowHibernation = "no";
    AllowHybridSleep = "no";
    AllowSuspendThenHibernate = "no";
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true;
      };
    };
  };
  services.blueman.enable = true;

  systemd.services.bluetooth-init = {
    description = "rfkill bluetooth persistence bug";
    after = ["bluetooth.service" "sys-subsystem-bluetooth-devices-hci0.device"];
    requires = ["bluetooth.service"];
    wantedBy = ["multi-user.target"];
    path = [pkgs.coreutils pkgs.util-linux];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = "yes";
      ExecStart = "${
        pkgs.writeShellScript "unblock-bluetooth" ''
          #!/usr/bin/env bash
          sleep 1; rfkill unblock bluetooth
        ''
      }";
    };
  };

  # Configure keymap in X11
  services.xserver = {
    enable = true; # Enable X11 windowing system

    xkb.layout = "se";
    xkb.variant = "";

    displayManager.gdm.enable = false; # GNOME Desktop Environment
  };
  services.displayManager.ly.enable = true;
  services.displayManager.ly.settings = {
    save = true;
    load = true;
  };

  services.desktopManager.gnome.enable = true;
  # services.libinput.mouse.accelProfile = "adaptive"; configured in hyprland.conf
  services.printing.enable = true;
  services.fwupd.enable = true; # Firmware updator
  services.system76-scheduler.enable = false;

  # services.throttled = {
  #   enable = true;
  #   extraConfig = ''
  #     [UNDERVOLT]
  #     # CPU core voltage offset (mV)
  #     CORE: -105
  #     # Integrated GPU voltage offset (mV)
  #     GPU: -85
  #     # CPU cache voltage offset (mV)
  #     CACHE: -105
  #     # System Agent voltage offset (mV)
  #     UNCORE: -85
  #     # Analog I/O voltage offset (mV)
  #     ANALOGIO: 0
  #   '';
  # };
  # services.undervolt = {
  #   enable = true;
  #   # useTimer = true;
  #   verbose = true;
  #   uncoreOffset = -75;
  #   turbo = 0;
  #   tempAc = 70;
  #   tempBat = 65;
  #   temp = 70;
  #   p2.window = 0.002;
  #   p2.limit = 90;
  #   p1.window = 28;
  #   p1.limit = 45;
  #   gpuOffset = -50;
  #   coreOffset = -50;
  #   analogioOffset = -50;
  # };
  # systemd.services.intel-undervolt = {
  #   description = "Intel Undervolt";
  #   after = ["multi-user.target"];
  #   wantedBy = ["multi-user.target"];
  #   serviceConfig = {
  #     Type = "oneshot";
  #     ExecStart = "${pkgs.writeShellScript "undavolt" ''
  #       #!/usr/bin/env bash
  #       PATH=$PATH:${lib.makeBinPath [pkgs.undervolt]}
  #       undervolt read & undervolt apply
  #     ''}";
  #   };
  # };
  services.power-profiles-daemon.enable = false;
  # services.auto-cpufreq = {
  #   enable = true;
  #   settings = {
  #     battery = {
  #       governor = "powersave";
  #       turbo = "never";
  #       preference = "power";
  #     };
  #     charger = {
  #       governor = "powersave";
  #       turbo = "never";
  #     };
  #   };
  # };

  systemd.user.services.niri.enableDefaultPath = false;

  services.envfs.enable = true;

  security.sudo = {
    enable = true;
    extraRules = [
      {
        commands = [
          {
            command = "${pkgs.systemd}/bin/reboot";
            options = ["NOPASSWD"];
          }
          {
            command = "${pkgs.systemd}/bin/poweroff";
            options = ["NOPASSWD"];
          }
        ];
        groups = ["wheel"];
      }
    ];
    extraConfig = with pkgs; ''
      Defaults:picloud secure_path="${lib.makeBinPath [
        systemd
      ]}:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"
    '';
  };

  programs.gnupg.agent = {
    enable = true;
    settings = {
      default-cache-ttl = 600;
      max-cache-ttl = 7200;
    };
  };

  programs.ydotool.enable = true;

  services.openssh.enable = true;

  services.udev.extraRules = ''
    KERNEL=="uinput", GROUP="input", MODE:="0660"
  '';

  # sops = {
  #   defaultSopsFile = ./secrets/hermes.yaml;
  #   age.keyFile = "/var/lib/sops-nix/key.txt";
  #   secrets."hermes-env" = {format = "yaml";};
  # };

  # services.hermes-agent = {
  #   enable = true;
  #   settings.model = {
  #     provider = "anthropic";
  #     default = "claude-sonnet-5";
  #   };
  #   environmentFiles = [config.sops.secrets."hermes-env".path];
  #   addToSystemPackages = true;
  # };

  nix.settings.substituters = ["https://attic.xuyh0120.win/lantian"];
  nix.settings.trusted-public-keys = ["lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc="];

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # kdeconnect
  networking.firewall = rec {
    allowedTCPPortRanges = [
      {
        from = 1714;
        to = 1764;
      }
    ];
    allowedUDPPortRanges = allowedTCPPortRanges;
    allowedTCPPorts = [8443];
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.11"; # Did you read the comment?
}
